### ISSUE TITLE
Caching option does not work

### ISSUE THREAD

**Issue by binarykitchen** [shama/gulp-webpack#45]
It seems that setting cache to true has no impact on webpack's gulp plugin.

**Comment by shama** [comment]
Does it work directly with webpack?

**Comment by binarykitchen** [comment]
No idea, documentation does not say much.

**Comment by shama** [comment]
You should probably make sure that is working first. Since this plugin doesn't do any caching, just interfaces with webpack itself, it's likely not an issue here. For general questions on how webpack works, try their https://gitter.im/webpack/webpack channel or stackoverflow. If you figure it out please add it to webpack's docs, they are freely editable.

**Comment by dazld** [comment]
This is actually an issue with the plugin, as it is creating a new instance of webpack on every run, as far as I can tell.

**Comment by jmurzy** [comment]
@shama — that'd be great if we could pass an instance of webpack to the plugin rather than webpack itself.
```javascript
const compiler = webpack(webpackConfig)
...
.pipe(webpackStream(compiler, cb))
```
For caching to work, we have to use [the same instance](https://github.com/webpack/webpack-with-common-libs/blob/master/gulpfile.js#L51) on subsequent compiles.
